name: deploy storybook

on:
    push:
        branches:
            - master
        paths:
            - '**.js'
            - '**.vue'
            - '**.css'

jobs:
    deploy-pages:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2.3.2
              with:
                  node-version: '13.x'
            - id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn cache dir)"
            - uses: actions/cache@v2.1.4
              id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-
            - run: yarn --frozen-lockfile
            - run: yarn storybook:build
            - uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ github.token }}
                  BRANCH: gh-pages # The branch the action should deploy to.
                  FOLDER: storybook-static # The folder the action should deploy.
                  CLEAN: true
